[advisories]
# By default, vulnerabilities are denied.
# We don't need to specify 'vulnerability = "deny"' anymore.

[licenses]
# By default, unlicensed and copyleft are denied.
# We only need to explicitly define what we choose to allow.
allow = [
    "MIT",
    "Apache-2.0",
]